package models.logistics;

public enum TypeMateriel {
    EQUIPEMENT_SPORTIF,   // Machines de musculation, tapis de course, vélos d’appartement...
    ACCESSOIRE_ENTRAINEMENT, // Cônes, échelles d’agilité, cordes à sauter...
    MATERIEL_JEU,         // Ballons (foot, basket, volley), filets, raquettes...
    TENUE_SPORTIVE,       // Maillots, shorts, survêtements, chaussures...
    EQUIPEMENT_PROTECTION, // Protège-tibias, casques, gants, genouillères...
    INFRASTRUCTURE
}
